[mcp_servers.context7]
command = "npx"
args = ["-y", "@upstash/context7-mcp"]

[mcp_servers.playwright]
command = "npx"
args = ["-y", "@playwright/mcp@latest"]

[mcp_servers.deepwiki]
command = "npx"
args = ["-y", "mcp-deepwiki@latest"]

[mcp_servers.magic]
command = "npx"
args = ["-y", "@21st-dev/magic@latest"]
env = { API_KEY = "$MAGIC_API_KEY" }

[mcp_servers.taskmaster-ai]
command = "npx"
args = ["-y", "--package=task-master-ai", "task-master-ai"]
