disable_response_storage = true

[mcp_servers.context7]
command = "npx"
args = ["-y", "@upstash/context7-mcp"]

[mcp_servers.deepwiki]
command = "npx"
args = ["-y", "mcp-deepwiki@latest"]

[mcp_servers.mcp-domain-availability]
command = "uvx"
args = ["--from", "git+https://github.com/imprvhub/mcp-domain-availability", "mcp-domain-availability"]

[mcp_servers.supabase]
command = "npx"
args = ["-y", "@supabase/mcp-server-supabase@latest"]
env = { SUPABASE_ACCESS_TOKEN = "$SUPABASE_ACCESS_TOKEN" }

[mcp_servers.chrome-devtools]
command = "npx"
args = ["chrome-devtools-mcp@latest", "--browser-url=http://127.0.0.1:9222"]
