format = """
$directory\
$git_branch\
$git_status\
$java\
$rust\
$nodejs\
$cmd_duration\
$character\
"""

add_newline = false
command_timeout = 1000

[directory]
truncation_length = 1
truncate_to_repo = false
truncation_symbol = '…/'
style = 'bold fg:39'
repo_root_style = 'bold fg:31'
before_repo_root_style = 'bold fg:39'

[git_branch]
format = '[$symbol $branch(:$remote_branch)]($style) '
style = 'bold fg:76'
symbol = "🚀"

[git_status]
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'

[java]
format = '[${symbol}(${version} )]($style)'
version_format = 'v${raw}'
symbol = "☕"

[nodejs]
format = '[$symbol ($version )]($style)'
symbol = "⬢"

[rust]
format = '[$symbol ($version )]($style)'
symbol = "🦀"

[cmd_duration]
min_time = 500
format = 'took [$duration]($style) '

