name: Test Install
on: [push]
concurrency:
  group: install-dotfiles-global
  cancel-in-progress: true
jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
    steps:
      - uses: actions/checkout@v2
      - name: Install dotfiles 
        run: ./install.sh -m minimal -y
