name: Test Install
on: [push]
jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-11.0, ubuntu-22.04]
    steps:
      - uses: actions/checkout@v2
      - name: Install dotfiles 
        run: ./install.sh -m minimal -y
